const fs = require("fs");
const path = require("path");
const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");

/**
 * Give Health Connect a privacy policy that actually renders.
 *
 * Health Connect's permission sheet shows a "Read privacy policy" link, and
 * fires `ACTION_SHOW_PERMISSIONS_RATIONALE` at whichever activity claims it.
 * react-native-health-connect's own plugin points that at MainActivity, which
 * is the React Native host — so the tap cold-started the whole app and left a
 * blank white screen while the bundle loaded, then landed on the login screen
 * rather than on any policy. Nothing was wired to handle the action in JS,
 * so the policy was simply never shown.
 *
 * The fix is to keep it out of React Native entirely: a plain Activity with a
 * WebView over a bundled HTML asset. It paints immediately, works before
 * sign-in, and cannot be affected by navigation state. The same activity also
 * backs the `VIEW_PERMISSION_USAGE` alias, which is the other surface Android
 * uses to ask an app for its health privacy policy.
 *
 * A config plugin rather than a hand edit for the same reason as
 * withCxxStagingDir: `android/` is generated and gitignored, so `expo prebuild`
 * would silently throw the edit away.
 */

const RATIONALE_ACTION = "androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE";
const ACTIVITY_NAME = ".PrivacyPolicyActivity";
const ASSET_NAME = "health-privacy-policy.html";
const SOURCE_HTML = path.join("privacy", "health-connect-policy.html");

/** True if this manifest node declares the Health Connect rationale action. */
function isRationaleFilter(filter) {
  return (filter.action || []).some(
    (action) => action.$ && action.$["android:name"] === RATIONALE_ACTION,
  );
}

function kotlinSource(packageName) {
  return `package ${packageName}

import android.app.Activity
import android.os.Bundle
import android.webkit.WebView
import java.util.Locale

/**
 * The privacy policy Health Connect links to from its permission sheet.
 *
 * Generated by mobile-app/plugins/withHealthPrivacyPolicy.js — edit that, not
 * this file, which \`expo prebuild\` rewrites.
 *
 * Deliberately a plain Activity rather than a React Native screen: Health
 * Connect opens this before the app has started and usually before anyone has
 * signed in, so routing it through the RN stack showed a blank white page.
 */
class PrivacyPolicyActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val language = when (Locale.getDefault().language) {
      "ru" -> "ru"
      "tr" -> "tr"
      else -> "en"
    }

    val web = WebView(this)
    // The page selects its language with CSS :target, so the fragment is not
    // decoration — without one, every section stays hidden.
    web.loadUrl("file:///android_asset/${ASSET_NAME}#" + language)
    setContentView(web)
  }
}
`;
}

/** Put the activity and its asset into a generated Android project. */
function writeNativeFiles(projectRoot, platformProjectRoot, packageName) {
  const main = path.join(platformProjectRoot, "app", "src", "main");

  const javaDir = path.join(main, "java", ...packageName.split("."));
  fs.mkdirSync(javaDir, { recursive: true });
  fs.writeFileSync(path.join(javaDir, "PrivacyPolicyActivity.kt"), kotlinSource(packageName));

  const source = path.join(projectRoot, SOURCE_HTML);
  if (!fs.existsSync(source)) {
    throw new Error(`withHealthPrivacyPolicy: missing ${SOURCE_HTML}`);
  }
  const assetsDir = path.join(main, "assets");
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.copyFileSync(source, path.join(assetsDir, ASSET_NAME));
}

module.exports = function withHealthPrivacyPolicy(config) {
  // 1. Manifest: take the action off MainActivity, give it to the new one.
  config = withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    for (const activity of app.activity || []) {
      if (activity["intent-filter"]) {
        activity["intent-filter"] = activity["intent-filter"].filter(
          (filter) => !isRationaleFilter(filter),
        );
      }
    }

    // The settings-side surface should show the policy too, not the app.
    for (const alias of app["activity-alias"] || []) {
      if (alias.$ && alias.$["android:targetActivity"] === ".MainActivity") {
        alias.$["android:targetActivity"] = ACTIVITY_NAME;
      }
    }

    app.activity = (app.activity || []).filter(
      (activity) => !activity.$ || activity.$["android:name"] !== ACTIVITY_NAME,
    );
    app.activity.push({
      $: {
        "android:name": ACTIVITY_NAME,
        "android:exported": "true",
        "android:label": "Privacy policy",
        // No action bar, and not the splash theme: this window is not the app.
        "android:theme": "@android:style/Theme.DeviceDefault.Light.NoActionBar",
      },
      "intent-filter": [{ action: [{ $: { "android:name": RATIONALE_ACTION } }] }],
    });

    return cfg;
  });

  // 2. Drop the Kotlin activity and the HTML asset into the generated project.
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const packageName = AndroidConfig.Package.getPackage(cfg);
      if (!packageName) throw new Error("withHealthPrivacyPolicy: android.package is not set");

      writeNativeFiles(
        cfg.modRequest.projectRoot,
        cfg.modRequest.platformProjectRoot,
        packageName,
      );
      return cfg;
    },
  ]);
};
