"""add workout route

Hand-written rather than autogenerated: `--autogenerate` needs a live database
to diff against, and the only one reachable from here is production.

Revision ID: c4a1b2d3e5f6
Revises: f9368356b4da
Create Date: 2026-08-30

The column is nullable so every existing row stays valid and clients that never
send a route keep working.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "c4a1b2d3e5f6"
down_revision = "f9368356b4da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("workouts", sa.Column("route", sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column("workouts", "route")
